"""Subclass of Designer, which is generated by wxFormBuilder."""

import wx
import beadgui

# Implementing Designer
class BeadDesignDesigner( beadgui.Designer ):
	def __init__( self, parent ):
		beadgui.Designer.__init__( self, parent )
	
	# Handlers for Designer events.
	def onGenerate( self, event ):
		# TODO: Implement onGenerate
		pass
	
	def onImage( self, event ):
		# TODO: Implement onImage
		pass
	
	def onView( self, event ):
		# TODO: Implement onView
		pass
	
	def onLoadImage( self, event ):
		# TODO: Implement onLoadImage
		pass
	
	def onExit( self, event ):
		# TODO: Implement onExit
		pass
	
	def onAbout( self, event ):
		# TODO: Implement onAbout
		pass
	
	
